disp('----------------------------------------------------------------------')
disp('-------------------- Sistemas Dinámicos 2 ----------------------------')
disp('----------------------------------------------------------------------')
disp('--------------------------- POR: -------------------------------------')
disp('----------------- Jose Miguel Henao Cardona --------------------------')
disp('----------------- Juan José Giraldo Jiménez --------------------------')
disp('----------------------------------------------------------------------')
disp('                                                                      ')
disp('---                     | Temas del curso |                        ---')
disp('______________________________________________________________________')
disp('--- 1. Reducción de un sistema de orden Superior.                  ---')
disp('--- 2. Análisis de estabilidad.                                    ---')
disp('--- 3. Reglas construcción del LGR.                                ---')
disp('--- 4. Diseño Controladores Análogos                               ---')
disp('--- 5. Parcial                                                     ---')
disp('--- 6. Reglas de Ziegler-Nichols para sintonizar controladores PID ---')
disp('--- 7. Control de Sistemas Discretos                               ---')
disp('--- 8. Sistemas de control Digital                                 ---')
disp('--- 9. Estabilidad de un sistema Discreto                          ---')
disp('--- 10. Taller 1.                                                  ---')
disp('--- 11. Criterio de Jury para la estabilidad de un Sistema Discreto---')
disp('--- 12. Método de ROOTH-HURTWITZ modificado                        ---')
disp('--- 13. Analisis de respuesta transitoria en regiones permanentes  ---')
disp('______________________________________________________________________')
disp('----------------------------------------------------------------------')